///////////////////////////////////////////////////////////
//  Basket.cs
//  Implementation of the Class Basket
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:30
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public class Basket {

		private string description;
		private int id;
		private double price;

		public Basket(){

		}

		~Basket(){

		}

		public string getDescription(){

			return "";
		}

		public int getId(){

			return 0;
		}

		public double getPrice(){

			return 0;
		}

	}//end Basket

	public class Basket {

		private List<Good> good_list;
		public Class Model m_Basket;
		public Class.User m_User;

		public Basket(){

		}

		~Basket(){

		}

		public void clearBasket(){

		}

		public List<Good> getGoodList(){

			return null;
		}

	}//end Basket

}//end namespace Class