///////////////////////////////////////////////////////////
//  DBController.cs
//  Implementation of the Class DBController
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:30
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public class DBController : IDAO {

		private int id;

		public DBController(){

		}

		~DBController(){

		}

		/// 
		/// <param name="obj"></param>
		public int add(Object obj){

			return 0;
		}

		/// 
		/// <param name="id"></param>
		/// <param name="obj"></param>
		public int change(int id, Object obj){

			return 0;
		}

		/// 
		/// <param name="obj"></param>
		public int delete(Object obj){

			return 0;
		}

		public Object getAll(){

			return null;
		}

		/// 
		/// <param name="id"></param>
		public int read(int id){

			return 0;
		}

	}//end DBController

	public class DBController {

		private int id;

		public DBController(){

		}

		~DBController(){

		}

		/// 
		/// <param name="startDate"></param>
		/// <param name="endDate"></param>
		public void getCostReport(DateTime startDate, DateTime endDate){

		}

		/// 
		/// <param name="date"></param>
		public void getMonthReport(DateTime date){

		}

		/// 
		/// <param name="count"></param>
		public void getMostPopularGoods(int count){

		}

		public void sign_out(){

		}

	}//end DBController

}//end namespace Class