///////////////////////////////////////////////////////////
//  DirectorController.cs
//  Implementation of the Class DirectorController
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:30
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public class DirectorController : MainController {

		public DirectorController(){

		}

		~DirectorController(){

		}

		/// 
		/// <param name="startDate"></param>
		/// <param name="endDate"></param>
		public void getCostReport(DateTime startDate, DateTime endDate){

		}

		/// 
		/// <param name="date"></param>
		public void getMonthReport(DateTime date){

		}

		/// 
		/// <param name="count"></param>
		public void getMostPopularGoods(int count){

		}

		public void sign_out(){

		}

	}//end DirectorController

}//end namespace Class