///////////////////////////////////////////////////////////
//  Director.cs
//  Implementation of the Class Director
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:30
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public class Director : User {

		public Director(){

		}

		~Director(){

		}

		/// 
		/// <param name="criteria"></param>
		public override Object findGood(string criteria){

			return null;
		}

		/// 
		/// <param name="startDate"></param>
		/// <param name="EndDate"></param>
		public int getCostReport(DateTime startDate, DateTime EndDate){

			return 0;
		}

		/// 
		/// <param name="date"></param>
		public int getMonthReport(DateTime date){

			return 0;
		}

		/// 
		/// <param name="count"></param>
		public int getMostPopularGoods(int count){

			return 0;
		}

		/// 
		/// <param name="id"></param>
		public override Object showGoodInfo(int id){

			return null;
		}

		public override void sign_out(){

		}

		public override void viewCatalog(){

		}

	}//end Director

}//end namespace Class