///////////////////////////////////////////////////////////
//  Guest.cs
//  Implementation of the Class Guest
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:31
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public class Guest : User {

		public Guest(){

		}

		~Guest(){

		}

		/// 
		/// <param name="criteria"></param>
		public override Object findGood(string criteria){

			return null;
		}

		/// 
		/// <param name="id"></param>
		public override Object showGoodInfo(int id){

			return null;
		}

		/// 
		/// <param name="login"></param>
		/// <param name="password"></param>
		public int signIn(String login, String password){

			return 0;
		}

		/// 
		/// <param name="name"></param>
		/// <param name="surname"></param>
		/// <param name="login"></param>
		/// <param name="password"></param>
		public int singUp(string name, string surname, string login, string password){

			return 0;
		}

		public override void viewBasket(){

		}

		public override void viewCatalog(){

		}

	}//end Guest

}//end namespace Class