///////////////////////////////////////////////////////////
//  IDAO.cs
//  Implementation of the Interface IDAO
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:31
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Class {
	public interface IDAO  {

		/// 
		/// <param name="obj"></param>
		void add(Object obj);

		/// 
		/// <param name="id"></param>
		/// <param name="newState"></param>
		void change(int id, Object newState);

		/// 
		/// <param name="obj"></param>
		void delete(Object obj);

		Object getAll();

		/// 
		/// <param name="id"></param>
		int read(int id);
	}//end IDAO

}//end namespace Class