///////////////////////////////////////////////////////////
//  Interface1.cs
//  Implementation of the Interface Interface1
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:31
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Class {
	public interface Interface1  {

	}//end Interface1

}//end namespace Class