///////////////////////////////////////////////////////////
//  IPayment.cs
//  Implementation of the Interface IPayment
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:31
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Class {
	public interface IPayment  {

		void createTransaction();

		string getMessage();

		bool getStatus();
	}//end IPayment

}//end namespace Class