///////////////////////////////////////////////////////////
//  MainController.cs
//  Implementation of the Class MainController
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:31
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Class {
	public class MainController {

		private DBController Data;

		public MainController(){

		}

		~MainController(){

		}

		public void Act(){

		}

		public void RedirectToAction(){

		}

	}//end MainController

}//end namespace Class