///////////////////////////////////////////////////////////
//  ManagerController.cs
//  Implementation of the Class ManagerController
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:31
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public class ManagerController : MainController {

		public ManagerController(){

		}

		~ManagerController(){

		}

		/// 
		/// <param name="good"></param>
		public bool addGood(Good good){

			return false;
		}

		/// 
		/// <param name="id"></param>
		/// <param name="newGood"></param>
		public bool changeGood(int id, Good newGood){

			return false;
		}

		/// 
		/// <param name="id"></param>
		public int deleteGood(int id){

			return 0;
		}

		/// 
		/// <param name="criteria"></param>
		public override Object findGood(string criteria){

			return null;
		}

		/// 
		/// <param name="id"></param>
		public override Object showGoodInfo(int id){

			return null;
		}

		/// 
		/// <param name="count"></param>
		public int showMostPopularGoods(int count){

			return 0;
		}

		public override void sign_out(){

		}

		public override void viewCatalog(){

		}

	}//end ManagerController

}//end namespace Class