///////////////////////////////////////////////////////////
//  Order.cs
//  Implementation of the Class Order
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:31
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Class {
	public class Order {

		private DateTime deliveryDate;
		private string deliveryPlace;
		private int id;
		private int id_transaction;
		private int id_user;
		private double price;

		public Order(){

		}

		~Order(){

		}

		/// 
		/// <param name="id"></param>
		/// <param name="delDate"></param>
		/// <param name="delPlace"></param>
		/// <param name="id_transaction"></param>
		/// <param name="id_user"></param>
		/// <param name="price"></param>
		public Order(int id, DateTime delDate, string delPlace, int id_transaction, int id_user, double price){

		}

		public string detDeliveryPlace(){

			return "";
		}

		public DateTime getDeliveryDate(){

			return null;
		}

		public int getId(){

			return 0;
		}

		public double getPrice(){

			return 0;
		}

		public int getTransactionId(){

			return 0;
		}

		public int getUserId(){

			return 0;
		}

	}//end Order

}//end namespace Class