///////////////////////////////////////////////////////////
//  Transaction.cs
//  Implementation of the Class Transaction
//  Generated by Enterprise Architect
//  Created on:      10-дек-2019 0:12:31
//  Original author: Mi Pro
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Class;
namespace Class {
	public class Transaction : IPayment {

		private int bank_account_id;
		private DateTime executeDate;
		private int id;
		private double price;
		public Class Model m_Order;

		public Transaction(){

		}

		~Transaction(){

		}

		/// 
		/// <param name="id"></param>
		/// <param name="execDate"></param>
		/// <param name="price"></param>
		/// <param name="bank_id"></param>
		public Transaction(int id, DateTime execDate, double price, int bank_id){

		}

		public void createTransaction(){

		}

		public int getBankAccountId(){

			return 0;
		}

		public DateTime getExecutionDate(){

			return null;
		}

		public string getMessage(){

			return "";
		}

		public double getPrice(){

			return 0;
		}

		public bool getStatus(){

			return false;
		}

	}//end Transaction

}//end namespace Class